#!/opt/local/bin/python

import sys
import time
from apphost.protocols import app_controller_client

if len(sys.argv) != 6:
    print "Usage: " + sys.argv[0] + " <username> <address> <port> <file_name> <label>"
    exit(1)

user_name = sys.argv[1]
address = sys.argv[2]
port = int(sys.argv[3])
file_name = sys.argv[4]
label = sys.argv[5]

acs = app_controller_client.AppControlClient(user_name,
                                             address,
                                             port)
while acs.alive is True and acs.get_state() == "INIT":
    time.sleep(1)

if acs.get_state() == "LOADED":
    # File already loaded!
    print "Server has file: " + acs.file_name + " : " + acs.md5sum
if acs.get_state() == "READY":
    acs.load(file_name, label)
    while acs.alive is True and acs.get_state() == "LOADING":
        time.sleep(1)
    if acs.get_state() == "LOADED":
        print "loaded file: " + acs.file_name + " : " + acs.md5sum

if acs.get_state() == "LOADED":
    acs.run("mycommand")

running = 0
while acs.alive is True and acs.get_state() != "ERROR":
    print acs.get_state()
    time.sleep(1)
    if acs.get_state() == "RUNNING":
        running += 1
        if running > 10:
            acs.stop()
            running = 0
    if acs.get_state() == "LOADED":
        acs.run("mycommand")
